import Head from "next/head";
import { Canvas } from "~/canvas/canvas";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sagadraw</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Canvas />
    </>
  );
}
